---
- name: Load the overlay module
  modprobe:
    name: overlay
    state: present
    persistent: present

- name: Load the bridge module
  modprobe:
    name: br_netfilter
    state: present
    persistent: present

- name: Update kernel settings
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  with_items:
    - net.bridge.bridge-nf-call-arptables
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

