---
- name: Update kernel net.bridge.bridge-nf-call-iptables
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  with_items:
    - net.bridge.bridge-nf-call-arptables
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: To ensure the br_netfilter.conf file exists, touch it
  file:
    path: /etc/modules-load.d/br_netfilter.conf
    state: touch

- name: Update the /etc/modules-load.d/br_netfilter.conf file to add the kubernetes comment
  lineinfile:
    path: /etc/modules-load.d/br_netfilter.conf
    regexp: '^# Load bridge netfilter'
    line: "# Load bridge netfilter module at boot. This is required by Kubernetes to allow bridging for iptables address translation."

- name: Update the /etc/modules-load.d/br_netfilter.conf file to activate the overlay module
  lineinfile:
    path: /etc/modules-load.d/br_netfilter.conf
    regexp: '^overlay'
    line: "overlay"

- name: Update the /etc/modules-load.d/br_netfilter.conf file to activate the bridge module
  lineinfile:
    path: /etc/modules-load.d/br_netfilter.conf
    regexp: '^br_netfilter'
    line: "br_netfilter"

