#!/bin/ksh

# Carl Schelin
# getquotas
#   Retrieves the resource values from deployments, daemonsets, and statefulsets plus gets resources from pods.
#   Copy to your home directory (I use ~/kubernetes/resources) and run. Directories are created for the 
#   cluster and then the types with a file with just the resources and the actual .yaml file

if [[ -z $1 ]]
then
  echo "Pass the site name"
  echo "icl-0, bldr0-0, gldn0-0, cabo0-0, hell0-0, tato0-1, alde0-0, lnmt1-2, miam1-1"
  exit 1
fi

SITE=$1

if [[ ! -d $SITE ]]
then
  mkdir $SITE
fi

context $SITE

for i in `kubectl get deploy -A | grep -v NAME | awk '{print $1":"$2}'`
do

  NAMESPACE=`echo $i | cut -f1 -d:`
  DEPLOY=`echo $i | cut -f2 -d:`

  if [[ ! -d $SITE/$NAMESPACE ]]
  then
    mkdir $SITE/$NAMESPACE
  fi

  echo "Namespace: $NAMESPACE,  Deployment: $DEPLOY"
  kubectl get deploy $DEPLOY -n $NAMESPACE -o json > $SITE/$NAMESPACE/$DEPLOY.deployment.yaml
  egrep -i "(resources|requests|limits|cpu|memory)" $SITE/$NAMESPACE/$DEPLOY.deployment.yaml > $SITE/$NAMESPACE/$DEPLOY.deployment

done

for i in `kubectl get daemonset -A | grep -v NAME | awk '{print $1":"$2}'`
do

  NAMESPACE=`echo $i | cut -f1 -d:`
  DAEMONSET=`echo $i | cut -f2 -d:`

  if [[ ! -d $SITE/$NAMESPACE ]]
  then
    mkdir $SITE/$NAMESPACE
  fi

  echo "Namespace: $NAMESPACE,  Daemonset: $DAEMONSET"
  kubectl get daemonset $DAEMONSET -n $NAMESPACE -o json > $SITE/$NAMESPACE/$DAEMONSET.daemonset.yaml
  egrep -i "(resources|requests|limits|cpu|memory)" $SITE/$NAMESPACE/$DAEMONSET.daemonset.yaml > $SITE/$NAMESPACE/$DAEMONSET.daemonset

done

for i in `kubectl get statefulset -A | grep -v NAME | awk '{print $1":"$2}'`
do

  NAMESPACE=`echo $i | cut -f1 -d:`
  STATEFULSET=`echo $i | cut -f2 -d:`

  if [[ ! -d $SITE/$NAMESPACE ]]
  then
    mkdir $SITE/$NAMESPACE
  fi

  echo "Namespace: $NAMESPACE,  Statefulset: $STATEFULSET"
  kubectl get statefulset $STATEFULSET -n $NAMESPACE -o json > $SITE/$NAMESPACE/$STATEFULSET.statefulset.yaml
  egrep -i "(resources|requests|limits|cpu|memory)" $SITE/$NAMESPACE/$STATEFULSET.statefulset.yaml > $SITE/$NAMESPACE/$STATEFULSET.statefulset

done

for i in `kubectl get pods -A | grep -v NAME | awk '{print $1":"$2}'`
do

  NAMESPACE=`echo $i | cut -f1 -d:`
  POD=`echo $i | cut -f2 -d:`

  if [[ ! -d $SITE/$NAMESPACE ]]
  then
    mkdir $SITE/$NAMESPACE
  fi

  echo "Namespace: $NAMESPACE,  Pod: $POD"
  kubectl get pod $POD -n $NAMESPACE -o json > $SITE/$NAMESPACE/$POD.pod.yaml
  egrep -i "(resources|requests|limits|cpu|memory)" $SITE/$NAMESPACE/$POD.pod.yaml > $SITE/$NAMESPACE/$POD.pod

done

