---
- name: Install Java
  yum:
    name: java
    state: latest

- name: Install versionlock
  yum:
    name: yum-plugin-versionlock
    state: latest

- name: Remove logstash lock
  command: /usr/bin/yum versionlock delete "logstash.*"

- name: Lock logstash at 7.10.0
  command: /usr/bin/yum versionlock add "logstash-7.10.0"

- name: Install logstash
  yum:
    name: logstash
    state: latest

- name: Enable logstash
  systemd:
    name: logstash
    enabled: yes

- name: Start logstash
  systemd:
    name: logstash
    state: restarted

