---
- name: Include Red Hat tasks
  include_tasks: "redhat.yaml"
  when: ansible_os_family == "RedHat"

- name: Include Debian tasks
  include_tasks: "debian.yaml"
  when: ansible_os_family == "Debian"

