# Author: Carl Schelin
# Purpose:
# This playbook runs all the different tasks that are needed to build the kubernetes environment.
---
- name: Configure the Kubernetes Servers
  hosts: "{{ pattern }}"
  become: true
  become_user: root
  gather_facts: yes

  roles:
    - { role: bridge,       tags: ["bridge"]       }
    - { role: swap,         tags: ["swap"]         }
    - { role: firewall,     tags: ["firewall"]     }
    - { role: packages,     tags: ["packages"]     }
    - { role: clustername,  tags: ["clustername"]  }
    - { role: kubelet,      tags: ["kubelet"]      }
    - { role: certificates, tags: ["certificates"] }
    - { role: logging,      tags: ["logging"]      }
    - { role: permissions,  tags: ["permissions"]  }
    - { role: kubeadm,      tags: ["kubeadm"]      }
    - { role: versionlock,  tags: ["versionlock"]  }
    - { role: postinstall,  tags: ["postinstall"]  }

