---
- name: Add Control Plane firewall services
  firewalld:
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{ item }}/tcp"
  with_items:
    - "6443"
    - "2379"
    - "2380"
    - "10250"
    - "10251"
    - "10252"
  when: "'kube' in inventory_hostname"
  notify: Start the firewalld Service

- name: Add Worker Node firewall services
  firewalld:
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{ item }}/tcp"
  with_items:
    - "10250"
    - "30000-32767"
  when: "'knode' in inventory_hostname"
  notify: Start the firewalld Service


