# Author: Carl Schelin
# Purpose:
# The core-dns container in Kubernetes has a bug in that if a container shares a worker with core-dns, name resolution fails.
# Since there are generally a pair of core-dns containers, the resolution lookup can succeed which throws off troubleshooting.
# The solution is to enable the three bridge kernel rules and enable the bridge module.
---
- name: Configure the bridge module and kernel settings for the core-dns container
  hosts: "{{ site }}"
  become: true
  become_user: root
  gather_facts: yes

  roles:
    - bridge

