---
- name: Remove bad lines (anything that doesn't list the existing time servers)
  lineinfile:
    dest: /etc/chrony.conf
    state: absent
    regexp: '^server {?!192\.168\.1\.254}'

- name: add in good lines
  lineinfile:
    dest: /etc/chrony.conf
    line: "{{ item.line }}"
    insertbefore: bof 
  with_items:
    - { line: "server 192.168.1.254" }

- name: Restart chrony
  systemd:
    daemon_reload: yes
    name: chronyd
    state: restarted

