apiVersion: v1
kind: ResourceQuota
metadata:
  name: 911net-resourcequota
  namespace: 911net
spec:
  hard:
    limits.cpu: "15600m"
    limits.memory: "37696Mi"
    requests.cpu: "13000m"
    requests.memory: "26624Mi"
