apiVersion: v1
kind: LimitRange
metadata:
  name: kube-system-limit-range
  namespace: kube-system
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 512m
    defaultRequest:
      memory: 256Mi
      cpu: 128m
    type: Container
