---
- name: Copy the 11-cgroups.conf kernel settings to the server
  copy:
    src: 11-cgroups.conf
    dest: /lib/systemd/system/kubelet.service.d/11-cgroups.conf
  notify: Start the kubelet and docker Services

