---
- name: Ensure manifest file permissions (CIS 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8)
  file:
    path: "/etc/kubernetes/manifests/{{ item.name }}"
    owner: "{{ item.owners }}"
    group: "{{ item.groups }}"
    mode: "{{ item.modes }}"
  with_items:
     - { name: kube-apiserver.yaml,          owners: root, groups: root, modes: '644' }
     - { name: kube-controller-manager.yaml, owners: root, groups: root, modes: '644' }
     - { name: kube-scheduler.yaml,          owners: root, groups: root, modes: '644' }
     - { name: etcd.yaml,                    owners: root, groups: root, modes: '644' }

- name: Ensure CNI file permissions (CIS 1.1.9, 1.1.10)
  file:
    path: "/etc/cni/net.d/{{ item.name }}"
    owner: "{{ item.owners }}"
    group: "{{ item.groups }}"
    mode: "{{ item.modes }}"
  with_items:
     - { name: 10-calico.conflist,  owners: root, groups: root, modes: '644' }
     - { name: calico-kubeconfig,   owners: root, groups: root, modes: '644' }

- name: Ensure permissions for /var/lib/etcd (CIS 1.1.11, 1.1.12)
  file:
    path: /var/lib/etcd
    owner: root
    group: root
    mode: '0700'

- name: Ensure Kubernetes file permissions (CIS 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18)
  file:
    path: "/etc/kubernetes/{{ item.name }}"
    owner: "{{ item.owners }}"
    group: "{{ item.groups }}"
    mode: "{{ item.modes }}"
  with_items:
     - { name: admin.conf,              owners: root, groups: root, modes: '644' }
     - { name: scheduler.conf,          owners: root, groups: root, modes: '644' }
     - { name: controller-manager.conf, owners: root, groups: root, modes: '644' }

- name: Ensure permissions for /etc/kubernetes/pki (CIS 1.1.19)
  file:
    path: /etc/kubernetes/pki
    owner: root
    group: root
    mode: '0755'

- name: Ensure pki *.crt/*.pub file permissions (CIS 1.1.20)
  file:
    path: "/etc/kubernetes/pki/{{ item.name }}"
    owner: "{{ item.owners }}"
    group: "{{ item.groups }}"
    mode: "{{ item.modes }}"
  with_items:
     - { name: ca.crt,                       owners: root, groups: root, modes: '644' }
     - { name: apiserver.crt,                owners: root, groups: root, modes: '644' }
     - { name: apiserver-kubelet-client.crt, owners: root, groups: root, modes: '644' }
     - { name: front-proxy-ca.crt,           owners: root, groups: root, modes: '644' }
     - { name: front-proxy-client.crt,       owners: root, groups: root, modes: '644' }
     - { name: sa.pub,                       owners: root, groups: root, modes: '644' }

- name: Ensure pki *.key file permissions (CIS 1.1.21)
  file:
    path: "/etc/kubernetes/pki/{{ item.name }}"
    owner: "{{ item.owners }}"
    group: "{{ item.groups }}"
    mode: "{{ item.modes }}"
  with_items:
     - { name: ca.key,                       owners: root, groups: root, modes: '600' }
     - { name: apiserver.key,                owners: root, groups: root, modes: '600' }
     - { name: apiserver-kubelet-client.key, owners: root, groups: root, modes: '600' }
     - { name: front-proxy-ca.key,           owners: root, groups: root, modes: '600' }
     - { name: front-proxy-client.key,       owners: root, groups: root, modes: '600' }
     - { name: sa.key,                       owners: root, groups: root, modes: '600' }

- name: Ensure permissions for /etc/kubernetes/pki/etcd
  file:
    path: /etc/kubernetes/pki/etcd
    owner: root
    group: root
    mode: '0755'

- name: Ensure etcd *.crt/*.pub file permissions
  file:
    path: "/etc/kubernetes/pki/etcd/{{ item.name }}"
    owner: "{{ item.owners }}"
    group: "{{ item.groups }}"
    mode: "{{ item.modes }}"
  with_items:
     - { name: ca.crt,                 owners: root, groups: root, modes: '644' }
     - { name: server.crt,             owners: root, groups: root, modes: '644' }
     - { name: peer.crt,               owners: root, groups: root, modes: '644' }
     - { name: healthcheck-client.crt, owners: root, groups: root, modes: '644' }

- name: Ensure pki *.key file permissions
  file:
    path: "/etc/kubernetes/pki/etcd/{{ item.name }}"
    owner: "{{ item.owners }}"
    group: "{{ item.groups }}"
    mode: "{{ item.modes }}"
  with_items:
     - { name: ca.key,                 owners: root, groups: root, modes: '600' }
     - { name: server.key,             owners: root, groups: root, modes: '600' }
     - { name: peer.key,               owners: root, groups: root, modes: '600' }
     - { name: healthcheck-client.key, owners: root, groups: root, modes: '600' }

