---
- name: "Create CentOS 7 Activation keys"
  theforeman.foreman.activation_key:
    username: "admin"
    password: "{{ katello_password }}"
    server_url: "{{ katello_url }}"
    organization: "{{ katello_organization }}"
    name: "Development CentOS 7 Key"
    lifecycle_environment: "Development"
    content_view: 'CentOS 7'
    description: "CentOS 7 Activation Key"
    auto_attach: yes
    unlimited_hosts: yes
    state: present
    subscriptions:
     - name: "CentOS 7 Linux"
  with_items:
    - Development
    - QA
    - Staging
    - Production

- name: "Create CentOS 8 Activation Keys"
  theforeman.foreman.activation_key:
    username: "admin"
    password: "{{ katello_password }}"
    server_url: "{{ katello_url }}"
    organization: "{{ katello_organization }}"
    name: "{{ item }} CentOS 8 Key"
    lifecycle_environment: "{{ item }}"
    content_view: 'CentOS 8'
    description: "CentOS 8 Activation Key"
    auto_attach: yes
    unlimited_hosts: yes
    state: present
    subscriptions:
     - name: "CentOS 8 Linux"
  with_items:
    - Development
    - QA
    - Staging
    - Production

