---
- name: Change {{ user }}'s development password
  user:
    name={{ user }}
    update_password=always
    password={{ envuser }}
  when: ('BLDR' in inventory_hostname|upper)

- name: Change {{ user }}'s qa password
  user:
    name={{ user }}
    update_password=always
    password={{ envuser }}
  when: ('CABO' in inventory_hostname|upper)

- name: Change {{ user }}'s staging password
  user:
    name={{ user }}
    update_password=always
    password={{ envuser }}
  when: ('TATO' in inventory_hostname|upper)

- name: Change {{ user }}'s production password
  user:
    name={{ user }}
    update_password=always
    password={{ envuser }}
  when: ('LNMT' in inventory_hostname|upper)

- name: Change {{ user }}'s personal password
  user:
    name={{ user }}
    update_password=always
    password={{ envuser }}
  when: ('NDLD' in inventory_hostname|upper)

- name: Ensure standard user resets password upon login, skip service accounts
  shell: chage -d 0 {{ user }}
  when: user != 'root' and user != 'unixsvc'

