---
- name: Change development password for {{ username }}
  user:
    name={{ username }}
    update_password=always
    password={{ boulder.password }}
  when: ('BLDR' in inventory_hostname|upper)

- name: Change qa password for {{ username }}
  user:
    name={{ username }}
    update_password=always
    password={{ cabo.password }}
  when: ('CABO' in inventory_hostname|upper)

- name: Change staging password for {{ username }}
  user:
    name={{ username }}
    update_password=always
    password={{ tatooine.password }}
  when: ('TATO' in inventory_hostname|upper)

- name: Change production password for {{ username }}
  user:
    name={{ username }}
    update_password=always
    password={{ longmont.password }}
  when: ('LNMT' in inventory_hostname|upper)

- name: Change personal password for {{ username }}
  user:
    name={{ username }}
    update_password=always
    password={{ nederland.password }}
  when: ('NDLD' in inventory_hostname|upper)

- name: Ensure standard username resets password upon login, skip service accounts
  shell: chage -d 0 {{ username }}
  when: username != 'root' and username != 'unixsvc'

