---
- name: Check for safety-systems.docker.west.com.pem
  stat: path=/etc/pki/ca-trust/source/anchors/safety-systems.docker.west.com.pem
  register: foobar

- name: Don't run it again if it already exists. Assumption is the other files exist as well.
  fail: msg="This host has already had this playbook run against it"
  when: foobar.stat.exists

# now add the correct file for docker, but also all the other files.
- name: Add IntradoCA.pem
  copy:
    src: ../files/IntradoCA.pem
    dest: /etc/pki/ca-trust/source/anchors/IntradoCA.pem

- name: Add safety-systems.docker.west.com.pem
  copy:
    src: ../files/safety-systems.docker.west.com.pem
    dest: /etc/pki/ca-trust/source/anchors/safety-systems.docker.west.com.pem

- name: Add WestCorpIssueCA3.cer  
  copy:
    src: ../files/WestCorpIssueCA3.cer  
    dest: /etc/pki/tls/certs/WestCorpIssueCA3.cer  

- name: Add WestCorporationIssueCA5_B64.cer  
  copy:
    src: ../files/WestCorporationIssueCA5_B64.cer  
    dest: /etc/pki/tls/certs/WestCorporationIssueCA5_B64.cer  

- name: Add WestCorporationRootCA_B64.cer  
  copy:
    src: ../files/WestCorporationRootCA_B64.cer  
    dest: /etc/pki/tls/certs/WestCorporationRootCA_B64.cer  

- name: Add WestCorpRootCA.cer
  copy:
    src: ../files/WestCorpRootCA.cer
    dest: /etc/pki/tls/certs/WestCorpRootCA.cer

- name: Trust the new certificates
  command: /usr/bin/update-ca-trust

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted

- name: Restart docker
  systemd:
    name: docker
    state: restarted

