---
# add the correct file for docker logging
- name: Add daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: Start the docker Service

- name: Correct the docker file
  replace:
    path: /etc/sysconfig/docker
    regexp: '--log-driver=journald'
    replace: ''
  notify: Start the docker Service

