---
- name: Create Products
  theforeman.foreman.product:
    username: "admin"
    password: "{{ katello_password }}"
    server_url: "{{ katello_url }}"
    organization: "{{ katello_organization }}"
    name: "{{ item }}"
    state: present
  with_items:
    - "CentOS 7 Linux"
    - "CentOS 8 Linux"
    - "Fedora EPEL 7 Linux"
    - "Fedora EPEL 8 Linux"
    - "Kubernetes"
    - "Elasticsearch"

