#!/bin/ksh

. /opt/unixsuite/rrdtool/config

# want to continually run stats at 15 second intervals
IOPID=999999
VMPID=999999

while true
do

  IOTST=`ps -e | grep $IOPID`
  if [[ -z "$IOTST" ]]
  then
    /usr/bin/iostat -dxt 15 >> $DATA/iostat.output 2>&1 &
    IOPID=$!
  fi

  VMTST=`ps -e | grep $VMPID`
  if [[ -z "$VMTST" ]]
  then
    /usr/bin/vmstat 15 >> $DATA/vmstat.output 2>&1 &
    VMPID=$!
  fi

  MPTST=`ps -e | grep $MPID`
  if [[ -z "$MPTST" ]]
  then
    /usr/bin/mpstat 5 >> $DATA/mpstat.output 2>&1 &
    MPID=$!
  fi

# swap stats
  /usr/sbin/swap -s > $DATA/swap.output

  sleep 15

done

