---
- name: Start the firewalld Service
  systemd:
    name: firewalld
    state: restarted
    enabled: yes

- name: Start the named Service
  systemd:
    name: named
    state: restarted
    enabled: yes

