---
- name: Configure the Kubernetes Servers
  hosts: "{{ pattern }}"
  become: true
  become_user: root
  gather_facts: no


pre_tasks:
  - name: Include common variables
    include_vars:
      file: ../../vars/common.yaml
    tags:
      - always

  roles:
    - { role: bridge,       tags: ["bridge"]       }
    - { role: swap,         tags: ["swap"]         }
    - { role: firewall,     tags: ["firewall"]     }
    - { role: packages,     tags: ["packages"]     }

