# Carl Schelin
# tag: terraform
# install kvm. This installs all the necessary files, starts libvirtd, makes the mount point, and updates the service account
# install terraform. Just copies a file out
# install the libvirt providor into the service account's home directory
# create the logical volume for images
# ansible-playbook -i /usr/local/admin/etc/hosts -e 'pattern=nikodemus' install_terraform --tags [initialize,kvm,terraform,provider,createlvm]
---
- hosts: "{{ pattern }}"
  become: true
  become_user: root
  gather_facts: no

  roles:
    - { role: initialize,  tag: ["initialize"] }
    - { role: kvm,         tag: ["kvm"] }
    - { role: terraform,   tag: ["terraform"] }
    - { role: provider,    tag: ["provider"] }
    - { role: createlvm,   tag: ["createlvm"] }

