---
- name: Install docker-distribution
  dnf:
    name: ['docker-distribution']
    state: present
    update_cache: yes
  notify:
  - Start the registry Service

- name: Install php for the website to display an image listing
  dnf:
    name: ['php']
    state: present
    update_cache: yes

- name: Install the httpd server
  dnf:
    name: ['httpd']
    state: present
    update_cache: yes
  notify:
  - Start the httpd Service

- name: Install the index.php file
  template:
    src: index.php.j2
    dest: /var/www/html/index.php
    owner: root
    group: root
    mode: 0644

- name: Open firewall ports for access to the repository
  firewalld:
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{ item }}"
  with_items:
    - 5000/tcp
  notify:
  - Start the firewalld Service

- name: Open firewall ports for access to the repository
  firewalld:
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
    service: "{{ item }}"
  with_items:
    - http
  notify:
  - Start the firewalld Service

