#!/bin/bash

# Carl Schelin
# update:
# Update sshd to fix the banner, issue, motd, and remote root access issues

function usage() {
  echo "Usage:"
  echo "update -ehp [pattern]"
  echo "where:"
  echo " -h help"
  echo " -e enable check - Enable --check to validate task"
  echo " -p pattern - The pattern in the searchansible hosts file to use"
  echo "  Run searchansible to see all patterns"
  echo "  Run searchansible [pattern] to see the servers associated with [pattern]"
}

if [[ $(id -u) -ne 5000 ]]
then
  echo "This script must be run by the unixsvc account."
  echo ""
  exit 1
fi

if [[ -z $1 ]]
then
  usage
  exit 0
fi

HOSTS="/usr/local/admin/etc/hosts"
OPTCHECK=''
OPTPATTERN=''
while getopts "ehp:" arg
do
  case $arg in
    e) OPTCHECK="--check"
       ;;
    p) OPTPATTERN="${OPTARG}"
       ;;
    h) usage
       exit 0
       ;;
  esac
done

# remove *.retry files
if [[ -f *.retry ]]
then
  rm *.retry
fi

if [[ ! -f ${HOSTS} ]]
then
  echo "You are not on an ansible server. ${HOSTS} not found."
  echo ""
  exit 1
fi

if [[ -z ${OPTPATTERN} ]]
then
  echo "Error: No pattern identified: ${OPTPATTERN}"
  echo ""
  usage
  exit 1
fi

if [[ ! -z ${OPTCHECK} ]]
then
  echo "Validation enabled. No changes will be made to the systems."
fi

/usr/local/bin/searchansible ${OPTPATTERN} > /dev/null 2>&1
if [[ $? -eq 0 ]]
then
  echo "Disabling the Firewall, installing ksh, ipa-client, and mailx"
  ansible-playbook -i ${HOSTS} ${OPTCHECK} -e pattern=${OPTPATTERN} newserver.yaml
else
  echo "Unable to locate ${OPTPATTERN} in the ${HOSTS} hosts file"
fi

