---
- name: Install Postgresql15
  dnf:
    name: '@postgresql:15/server'
    state: present

- name: "Find out if PostgreSQL is initialized"
  stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "Initialize PostgreSQL"
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: Start the postgresql Service
  systemd:
    name: postgresql
    enabled: yes
    state: restarted

