---
- name: Install Postgresql15
  dnf:
    name: '@postgresql:15/server'
    state: present

- name: Start the postgresql Service
  systemd:
    name: postgresql
    enabled: yes
    state: restarted

