---
- name: Install Postgresql15
  dnf:
    name: '@postgresql:15/server'
    state: present

- name: Start the postgresql-server Service
  systemd:
    name: postgresql-server
    enabled: yes
    state: restarted

