#!/bin/ksh

# Carl Schelin
# context
# Lets you display your current context and change easily

function usage {
  echo "Usage: context [site]"
  echo "where:"
  echo "site - site name to change contexts"
  echo ""
  kubectl config get-contexts
}


if [[ -z $1 ]]
then
  usage
else

  case $1 in
    bldr) ARG="bldr"
       ;;
    cabo) ARG="cabo"
       ;;
    tato) ARG="tato"
       ;;
    lnmt) ARG="lnmt"
       ;;
    *) ARG=$1
       ;;
  esac

  if [[ -z $ARG ]]
  then
    usage
  else
    kubectl config use-context kubernetes-admin@${ARG}
    PS1="`uname`:kubernetes-admin@${ARG} "; export PS1
    kubectl get pods -A
  fi

fi

