---
- name: Install the necessary KVM packages
  apt:
    pkg:
    - qemu
    - qemu-kvm
    - libvirt-daemon
    - libvirt-clients
    - bridge-utils
    - virt-manager
    - libguestfs-tools
    - libvirt-dev

- name: Is security_driver already set to 'none'
  lineinfile:
    state: absent
    path: /etc/libvirt/qemu.conf
    regexp: '^security_driver = "none"'
  check_mode: true
  changed_when: false
  register: check

- name: Add the security_driver line if missing
  lineinfile:
    state: present
    path: /etc/libvirt/qemu.conf
    line: 'security_driver = "none"'
  when: check.found == 0

- name: Activate libvirtd
  systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: Create Image directory
  file:
    path: /libvirt_images
    state: directory

- name: Append the service account with the kvm groups
  user:
    name: unixsvc
    comment: "Unix Service Account"
    uid: 5000
    group: unixsvc
    groups: sudo,sysadmin,libvirt,kvm

