---
- name: Create CentOS 7 GPG Key
  theforeman.foreman.content_credential:
    username: "admin"
    password: "{{ katello_password }}"
    server_url: "{{ katello_url }}"
    organization: "{{ katello_organization }}"
    name: "RPM-GPG-KEY-CentOS-7"
    content_type: gpg_key
    content: "{{ lookup('file', 'RPM-GPG-KEY-CentOS-7') }}"

- name: Create EPEL 7 GPG Key
  theforeman.foreman.content_credential:
    username: "admin"
    password: "{{ katello_password }}"
    server_url: "{{ katello_url }}"
    organization: "{{ katello_organization }}"
    name: "RPM-GPG-KEY-EPEL-7"
    content_type: gpg_key
    content: "{{ lookup('file', 'RPM-GPG-KEY-EPEL-7') }}"

- name: Create CentOS 8 GPG Key
  theforeman.foreman.content_credential:
    username: "admin"
    password: "{{ katello_password }}"
    server_url: "{{ katello_url }}"
    organization: "{{ katello_organization }}"
    name: "RPM-GPG-KEY-CentOS-8"
    content_type: gpg_key
    content: "{{ lookup('file', 'RPM-GPG-KEY-CentOS-Official') }}"

- name: Create EPEL 8 GPG Key
  theforeman.foreman.content_credential:
    username: "admin"
    password: "{{ katello_password }}"
    server_url: "{{ katello_url }}"
    organization: "{{ katello_organization }}"
    name: "RPM-GPG-KEY-EPEL-8"
    content_type: gpg_key
    content: "{{ lookup('file', 'RPM-GPG-KEY-EPEL-8') }}"

- name: Create Google GPG Key
  theforeman.foreman.content_credential:
    username: "admin"
    password: "{{ katello_password }}"
    server_url: "{{ katello_url }}"
    organization: "{{ katello_organization }}"
    name: "RPM-GPG-KEY-google-cloud"
    content_type: gpg_key
    content: "{{ lookup('file', 'RPM-GPG-KEY-google-cloud') }}"

- name: Create Google GPG Key
  theforeman.foreman.content_credential:
    username: "admin"
    password: "{{ katello_password }}"
    server_url: "{{ katello_url }}"
    organization: "{{ katello_organization }}"
    name: "RPM-GPG-KEY-google-rapture"
    content_type: gpg_key
    content: "{{ lookup('file', 'RPM-GPG-KEY-google-rapture') }}"

- name: Create Elasticsearch GPG Key
  theforeman.foreman.content_credential:
    username: "admin"
    password: "{{ katello_password }}"
    server_url: "{{ katello_url }}"
    organization: "{{ katello_organization }}"
    name: "RPM-GPG-KEY-Elasticsearch"
    content_type: gpg_key
    content: "{{ lookup('file', 'RPM-GPG-KEY-elasticsearch') }}"

