#!/bin/bash

# Carl Schelin
# update:
# Update the chrony information on all servers

function usage() {
  echo "Ensure the local time server is in use"
  echo "Usage:"
  echo "update -eht [site] "
  echo "where:"
  echo " -h help"
  echo " -e enable check - Enable --check to validate task"
  echo " -t tag to apply this to. Replace spaces with underscores"
}

if [[ $(id -u) -ne 5000 ]]
then
  echo "This script must be run by the unixsvc account."
  echo ""
  exit 1
fi

if [[ -z $1 ]]
then
  usage
  exit 0
fi

HOSTS="/usr/local/admin/etc/hosts"
OPTCHECK=''
OPTTAG=''
while getopts "eht:" arg
do
  case $arg in
    e) OPTCHECK="--check"
       ;;
    t) OPTTAG="${OPTARG}"
       ;;
    h) usage
       exit 0
       ;;
  esac
done

# remove *.retry files
if [[ -f *.retry ]]
then
  rm *.retry
fi

if [[ ! -f ${HOSTS} ]]
then
  echo "You are not on an ansible server. ${HOSTS} not found."
  echo ""
  exit 1
fi

if [[ -z ${OPTTAG} ]]
then
  echo "Error: No tag found."
  echo ""
  usage
  exit 0
fi

/usr/local/bin/searchansible ${OPTTAG} > /dev/null 2>&1
if [[ $? -eq 0 ]]
then
  echo "Update chrony.conf information"
  ansible-playbook -i ${HOSTS} --extra-vars "site=${OPTTAG}" ${OPTCHECK} chrony.yaml
else
  echo "Unable to locate ${OPTTAG} in the ${HOSTS} hosts file"
fi

