# ansible-playbook -i /usr/local/admin/etc/hosts -e 'pattern=boulder:&elk:&logstash' logstash.yaml -C
---
- hosts: "{{ pattern }}"
  become: true
  become_user: root
  gather_facts: yes

  roles:
    - logstash

