#!/bin/ksh

function usage {
  echo "dnslabel [site]"
  echo "  where site is:"
  echo "    Dev: bldr"
  echo "    SQA: cabo"
  echo "    Stage: tato"
  echo "    Prod: lnmt"

}

if [[ -z $1 ]]
then
  usage
  exit 1
fi

CONTEXT=$1

case ${CONTEXT} in
  "bldr") COUNT="01 02 03"
          ;;
  "cabo") COUNT="01 02 03"
          ;;
  "tato") COUNT="01 02 03"
          ;;
  "lnmt") COUNT="01 02 03"
          ;;
esac

/usr/local/bin/context ${CONTEXT}

for i in ${COUNT}
do

  case ${CONTEXT} in 
    "bldr") SITE="bldr0cuomknode${i}.internal.pri"
            VERIFY="curl -m 5 -vv https://inventory.internal.pri"
            ;;
    "cabo") SITE="cabo0cuomknode{i}.internal.pri"
            VERIFY="curl -m 5 -vv https://inventory.internal.pri"

            ;;
    "tato") SITE="tato0cuomknode${i}.internal.pri"
            VERIFY="curl -m 5 -vv https://inventory.internal.pri"
            ;;
    "lnmt") SITE="lnmt1cuomknode${i}.internal.pri"
            VERIFY="curl -m 5 -vv https://inventory.internal.pri"
            ;;
  esac

  if [[ ! -z ${SITE} ]]
  then
    kubectl label nodes ${SITE} trouble=dnstools

    echo "Verify: ${VERIFY}"
    kubectl run --restart=Never -it --image bldr0cuomrepo1.internal.pri:5000/infoblox/dnstools dnstools --overrides='{"apiVersion": "v1", "spec": {"nodeSelector": { "trouble": "dnstools" }}}'

    kubectl delete pod dnstools -n kube-system

    kubectl label nodes ${SITE} trouble-
  fi

done

