---
- name: Install versionlock
  yum:
    name: yum-plugin-versionlock
    state: latest

- name: Remove kibana lock
  command: /usr/bin/yum versionlock delete "kibana.*"

- name: Lock kibana at 7.10.0
  command: /usr/bin/yum versionlock add "kibana-7.10.0*"

- name: Install kibana
  yum:
    name: kibana
    state: latest

- name: Enable kibana
  systemd:
    name: kibana
    enabled: yes

- name: Start kibana
  systemd:
    name: kibana
    state: restarted

