---
- name: Install versionlock
  yum:
    name: yum-plugin-versionlock
    state: latest

- name: Remove kibana 7.5.0-1 lock
  command: /usr/bin/yum versionlock delete "kibana-7.5.0-1.*"

- name: Lock kibana at 7.8.0
  command: /usr/bin/yum versionlock add "kibana-7.8.0*"

- name: Install kibana
  yum:
    name: kibana
    state: latest

- name: Enable kibana
  systemd:
    name: kibana
    enabled: yes

- name: Start kibana
  systemd:
    name: kibana
    state: restarted

