#  ansible-playbook -i /usr/local/admin/etc/hosts -e 'pattern=boulder:&mariadb' mariadb.yaml -C
---
- hosts: "{{ pattern }}"
  become: true
  become_user: root
  gather_facts: no

  roles:
    - mariadb
