#!/bin/bash

# Carl Schelin
# update:
# Update the permissions for all files

function usage() {
  echo "Updates ownership and permissions for all files."
  echo "Usage:"
  echo "update -eht [tag] "
  echo "where:"
  echo " -h help"
  echo " -e enable check - Enable --check to validate task"
  echo " -t the tag which identifies the cluster to update"
  echo "    use 'searchansible' to list possible tags"
}

if [[ $(id -u) -ne 5000 ]]
then
  echo "This script must be run by the unixsvc account."
  echo ""
  exit 1
fi

if [[ -z $1 ]]
then
  usage
  exit 0
fi

HOSTS="/usr/local/admin/etc/hosts"
OPTTAG=''
while getopts "eht:" arg
do
  case $arg in
    e) OPTCHECK="--check"
       ;;
    t) OPTTAG="${OPTARG}"
       ;;
    h) usage
       exit 0
       ;;
  esac
done

# remove *.retry files
if [[ -f *.retry ]]
then
  rm *.retry
fi

if [[ ! -f ${HOSTS} ]]
then
  echo "You are not on an ansible server. ${HOSTS} not found."
  echo ""
  exit 1
fi

if [[ -z ${OPTTAG} ]]
then
  echo "Error: you must pass a tag value"
  echo ""
  usage
  exit 0
fi

/usr/local/bin/searchansible ${OPTTAG} > /dev/null 2>&1
if [[ $? -eq 0 ]]
then
  echo "Set permissions per the CIS Kubernetes Benchmark v1.5.0 Document"
  ansible-playbook -i ${HOSTS} --extra-vars "site=${OPTTAG}" ${OPTCHECK} permissions.yaml
else
  echo "Unable to locate ${OPTTAG} in the ${HOSTS} hosts file"
fi

