#!/bin/bash

# Carl Schelin
# update:
# Update the permissions for all files

HOSTFILE=/usr/local/admin/etc/hosts

function usage() {
  echo "Usage:"
  echo "update -ehs [site] "
  echo "where:"
  echo " -h help"
  echo " -e enable check - Enable --check to validate task"
  echo " -s site - Site to modify"
  echo "    Dev sites: bldr0-0 gldn0-0"
  echo "    SQA sites: cabo0-0 hell0-0"
  echo "    CIL sites: alde0-0 tato0-1"
  echo "    Production sites: lnmt1-2 miam1-1"
}

if [[ $(id -u) -ne 5000 ]]
then
  echo "This script must be run by the unixsvc account."
  echo ""
  exit 1
fi

if [[ -z $1 ]]
then
  usage
  exit 0
fi

HOSTS="/usr/local/admin/etc/hosts"
OPTSITE=''
while getopts "ehs:" arg
do
  case $arg in
    e) OPTCHECK="--check"
       ;;
    s) OPTSITE="${OPTARG}"
       ;;
    h) usage
       exit 0
       ;;
  esac
done

# remove *.retry files
if [[ -f *.retry ]]
then
  rm *.retry
fi

if [[ ! -f ${HOSTS} ]]
then
  echo "You are not on an ansible server. ${HOSTS} not found."
  echo ""
  exit 1
fi

if [[ -z ${OPTSITE} ]]
then
  echo "Error: No configured site: ${OPTSITE}"
  echo ""
  usage
  exit 0
fi

/usr/local/bin/searchansible ${OPTSITE} > /dev/null 2>&1
if [[ $? -eq 0 ]]
then
  echo "Set permissions per the CIS Kubernetes Benchmark v1.5.0 Document"
  ansible-playbook -i ${HOSTFILE} --extra-vars "site=${OPTSITE}" ${OPTCHECK} permissions.yaml -s
else
  echo "Unable to locate ${OPTSITE} in the ${HOSTFILE} hosts file"
fi

