#!/bin/bash

# Carl Schelin
# update:
# update the cluster name and other variables for the kubernetes servers

function usage() {
  echo "Usage:"
  echo "update -ehs [site]"
  echo "where:"
  echo " -h help"
  echo " -e enable check - Enable --check to validate task"
  echo " -l DISABLE log file; output is to the screen"
  echo " -s site - Site to attach"
  echo "    sandbox site: icl-0"
  echo "    Dev site: gldn0-0 bldr0-0"
  echo "    SQA site: cabo0-0 hell0-0"
  echo "    CIL site: alde0-0 tato0-1"
  echo "    Production sites: lnmt1-2 miam1-1"
}

if [[ -z $1 ]]
then
  usage
  exit 0
fi

OPTCHECK=''
OPTSITE=''
OPTUSER=''
OPTLOG="clustername.log"
while getopts "ehs:l" arg
do
  case $arg in
    e) OPTCHECK="--check"
       ;;
    s) OPTSITE="${OPTARG}"
       ;;
    l) OPTLOG="/dev/stdout"
       ;;
    h) usage
       exit 0
       ;;
  esac
done

# remove *.retry files
if [[ -f *.retry ]]
then
  rm *.retry
fi

if [[ -z ${OPTSITE} ]]
then
  echo "Error: No configured site: ${OPTSITE}"
  echo ""
  usage
  exit 1
fi

if [[ ! -z ${OPTCHECK} ]]
then
  echo "Validation enabled. No changes will be made to the systems."
fi

echo "Upgrade Satellite to 6.5"
ansible-playbook -i /usr/local/admin/etc/hosts ${OPTCHECK} -e site=${OPTSITE} upgrade.yaml -s 

