#!/bin/ksh

# Carl Schelin
# context
# Lets you display your current context and change easily

USERNAME=$USER

if [[ ! -z $2 ]]
then
  LEVEL=$2
else
  LEVEL='admin'
fi

function usage {
  echo "Usage: context [site] [level]"
  echo "where:"
  echo "site - site name to change contexts; both bldr and bldr0-0 will work"
  echo "level/namespace - the access level or namespace; admin or view for access level or your namespace for namespace"
  echo ""
  kubectl config get-contexts
}


if [[ -z $1 ]]
then
  usage
else

  case $1 in
    bldr) ARG="bldr0-0"
       ;;
    cabo) ARG="cabo0-0"
       ;;
    tato) ARG="tato0-1"
       ;;
    lnmt) ARG="lnmt1-2"
       ;;
    *) ARG=$1
       ;;
  esac

  if [[ -z $ARG ]]
  then
    usage
  else
    kubectl config use-context $USERNAME-$LEVEL-$ARG-context
    PS1="`uname`:$LOGNAME@Cluster: $ARG$ "; export PS1
    if [[ $LEVEL = 'admin' ]]
    then
      kubectl get nodes
    else
      if [[ $LEVEL = 'view' ]]
      then
        kubectl get namespaces
      else
        kubectl get pods -n $LEVEL
      fi
    fi
  fi

fi

