---
- name: Create the mariadb directory if missing
  file:
    path: /etc/systemd/system/mariadb.service.d
    state: directory

- name: Copy mariadb settings file that changes privatetmp to false
  copy:
    src: ../files/privatetmp.conf
    dest: /etc/systemd/system/mariadb.service.d/

- name: restart mariadb
  systemd:
    name: mariadb
    daemon-reload: yes
    state: restarted

