# Assuming the VG is already in place, create a file system, format it, and mount it.
# this assumes of course that the LV doesn't yet exist.
# Carl Schelin
# 2017-05-12
# 
---
- name: Include Red Hat tasks
  include_tasks: "redhat.yaml"
  when: ansible_os_family == "RedHat"

- name: Include Debian tasks
  include_tasks: "debian.yaml"
  when: ansible_os_family == "Debian"

- name: Update permissions and ownerships of downloads
  file:
    path: /opt/downloads
    owner: unixsvc
    group: sysadmin
    mode: 0775

- name: Update permissions and ownerships of libvirt_images
  file:
    path: /opt/libvirt_images
    owner: unixsvc
    group: sysadmin
    mode: 0775

- name: Copy over the images
  copy:
    src: '{{ item }}'
    dest: '/opt/downloads/'
  loop:
    - bionic-server-cloudimg-amd64.img
    - centos7_300g.qcow2
    - centos8_120g.qcow2
    - centos8_20g.qcow2
    - centos8_50g.qcow2
    - centos8_75g.qcow2
    - CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2
    - debian10_20g.qcow2
    - debian-10-openstack-amd64.qcow2
    - ubuntu18_20g.img

