# ansible-playbook -i /usr/local/admin/etc/hosts -e 'pattern=boulder' -e 'user=root' -e 'envuser=boulderroot' pwreset.yaml -C
---
- name: Change passwords
  hosts: "{{ pattern }}"
  become: yes
  gather_facts: yes

  roles:
  - pwreset

