#!/bin/bash

# Carl Schelin
# update:
# Update 

function usage() {
  echo "Usage:"
  echo "update -eht [tag]"
  echo "where:"
  echo " -h help"
  echo " -e enable check - Enable --check to validate task"
  echo " -t tag - Tag for the list of servers"
  echo "  Run searchansible to see all tags"
  echo "  Run searchansible [tag] to see the servers associated with [tag]"
}

if [[ $(id -u) -ne 5000 ]]
then
  echo "This script must be run by the unixsvc account."
  echo ""
  exit 1
fi

if [[ -z $1 ]]
then
  usage
  exit 0
fi

PLAYBOOK=yum.yaml
HOSTS="/usr/local/admin/etc/hosts"
OPTCHECK=''
OPTTAG=''
while getopts "eht:" arg
do
  case $arg in
    e) OPTCHECK="--check"
       ;;
    t) OPTTAG="${OPTARG}"
       ;;
    h) usage
       exit 0
       ;;
  esac
done

# remove *.retry files
if [[ -f *.retry ]]
then
  rm *.retry
fi

if [[ ! -f ${HOSTS} ]]
then
  echo "You are not on an ansible server. ${HOSTS} not found."
  echo ""
  exit 1
fi

if [[ -z ${OPTTAG} ]]
then
  echo "Error: No configured site: ${OPTTAG}"
  echo ""
  usage
  exit 1
fi

if [[ ! -z ${OPTCHECK} ]]
then
  echo "Validation enabled. No changes will be made to the systems."
fi

echo "WARNING!!! This playbook runs a 'yum upgrade -y' on the server."
echo "           If this isn't what you want to do, Ctrl-C now!!!"
read

echo "WARNING!!! Just in case, if you're sure you want to upgrade the server,"
echo             hit ENTER, otherwise Ctrl-C out now!"
read

/usr/local/bin/searchansible ${OPTSITE} > /dev/null 2>&1
if [[ $? -eq 0 ]]
then
  echo "Update sshd"
  ansible-playbook -i ${HOSTS} ${OPTCHECK} -e pattern=${OPTTAG} ${PLAYBOOK}
else
  echo "Unable to locate ${OPTTAG} in the ${HOSTS} hosts file"
fi

