#!/bin/bash

# Carl Schelin
# checkmotd:
# run a basic yml script to make sure access to all systems is still in place
# report any fatals to the admins

ADMIN=/usr/local/admin
PLAYBOOK=$ADMIN/playbooks/cschelin/touchmotd
HOSTS="$ADMIN/etc/hosts"

WHOCARES=cschelin@internal.pri

if [[ $(id -u) -ne 5000 ]]
then
  echo "This script must be run by the unixsvc account."
  echo ""
  exit 1
fi

if [[ ! -f ${HOSTS} ]]
then
  echo "You are not on an ansible server. ${HOSTS} not found."
  echo ""
  exit 1
fi

ansible-playbook -i ${HOSTS} $PLAYBOOK/touchmotd.yml > $PLAYBOOK/touchmotd.log

grep fatal $PLAYBOOK/touchmotd.log > $PLAYBOOK/touchmotd.fatal

if [[ -s $PLAYBOOK/touchmotd.fatal ]]
then
  echo "The sanity check touches /etc/motd on all servers using the touchmotd.yml file. The results are any 'fatal' errors in contacting servers." > $PLAYBOOK/touchmotd.header
  echo "" >> $PLAYBOOK/touchmotd.header
  echo "" >> $PLAYBOOK/touchmotd.header
  cat $PLAYBOOK/touchmotd.header $PLAYBOOK/touchmotd.fatal | mailx -s "Ansible Sanity Check" $WHOCARES
fi

