#!/bin/bash

# Carl Schelin
# update:
# Install Kibana on the Elastic Stack servers

function usage() {
  echo "Usage:"
  echo "update -eht [tag]"
  echo "where:"
  echo " -h help"
  echo " -e enable check - Enable --check to validate task"
  echo " -t tag to use"
}

if [[ -z $1 ]]
then
  usage
  exit 0
fi

HOSTS="/usr/local/admin/etc/hosts"
OPTCHECK=''
OPTTAG=''
OPTUSER=''
while getopts "eht:" arg
do
  case $arg in
    e) OPTCHECK="--check"
       ;;
    t) OPTTAG="${OPTARG}"
       ;;
    h) usage
       exit 0
       ;;
  esac
done

# remove *.retry files
if [[ -f *.retry ]]
then
  rm *.retry
fi

if [[ -z ${OPTTAG} ]]
then
  echo "Error: No tag configured"
  echo ""
  usage
  exit 1
fi

if [[ ! -z ${OPTCHECK} ]]
then
  echo "Validation enabled. No changes will be made to the systems."
fi

echo "Create Kibana Node"
ansible-playbook -i ${HOSTS} ${OPTCHECK} -e tag=${OPTTAG} kibana.yaml

