# Carl Schelin
# Add clustername to the controller
---
- name: Include site variables for "{{ site }}"
  include_vars:
    file: "vars/{{ site }}.yaml"

- name: Add clustername
  lineinfile:
    dest: /etc/kubernetes/manifests/kube-controller-manager.yaml
    state: present
    regexp:       '    - --cluster-name={{ cluster_name }}'
    insertbefore: '    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt'
    line:         '    - --cluster-name={{ cluster_name }}'

