---
- name: Disable kubelet
  systemd:
    name: "{{ item.name }}"
    enabled: no
  with_items:
    - { name: kubelet }
    - { name: docker }

- name: Reboot server and stand by...
  reboot:

- name: Remove packages
  yum:
    name: "{{ packages }}"
    state: removed
  vars:
    packages:
    - docker
    - docker-client
    - docker-common
    - docker-rhel-push-plugin
    - kubeadm
    - kubectl
    - kubelet

- name: Delete CNI Files
  file:
    path: "{{ item.name }}"
    state: absent
  with_items:
     - { name: /etc/cni }
     - { name: /var/lib/cni }
     - { name: /var/lib/calico }

- name: Delete Docker Files
  file:
    path: "{{ item.name }}"
    state: absent
  with_items:
     - { name: /etc/docker }
     - { name: /var/lib/docker }
     - { name: /var/lib/dockershim }

- name: Delete Kubernetes Files
  file:
    path: "{{ item.name }}"
    state: absent
  with_items:
     - { name: /etc/kubernetes }
     - { name: /var/lib/kubelet }

- name: Does /var/lib/etcd exist (only on masters)
  stat: path=/var/lib/etcd
  register: foobar

- name: Delete /var/lib/etcd but only on masters
  file:
    path: /var/lib/etcd
    state: absent
  when: foobar.stat.exists == True

