---
- name: Copy the influxdb repo 
  copy:
    src: ../files/influxdb.repo
    dest: /etc/yum.repos.d/influxdb.repo

- name: Install telegraf
  yum:
    name: telegraf
    state: latest

- name: Install main telegraf configuration
  template:
    src: templates/telegraf.conf
    dest: "/etc/telegraf/telegraf.conf"
    mode: 0644
  with_items: "{{ config }}"

- name: Install main telegraf core file
  template:
    src: templates/core.conf
    dest: "/etc/telegraf/telegraf.d/core.conf"
    mode: 0644
  with_items: "{{ config }}"

#- name: Enable and start the telegraf service
#  systemd:
#    name: telegraf
#    state: started
#    enabled: yes

