---
- name: Update the etcd imagePullPolicy
  replace:
    dest: /etc/kubernetes/manifests/etcd.yaml
    replace: '    imagePullPolicy: Always'
    regexp: '^    imagePullPolicy: IfNotPresent'

- name: Update the kube-apiserver imagePullPolicy
  replace:
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    replace: '    imagePullPolicy: Always'
    regexp: '^    imagePullPolicy: IfNotPresent'

- name: Update the kube-controller-manager imagePullPolicy
  replace:
    dest: /etc/kubernetes/manifests/kube-controller-manager.yaml
    replace: '    imagePullPolicy: Always'
    regexp: '^    imagePullPolicy: IfNotPresent'

- name: Update the kube-scheduler imagePullPolicy
  replace:
    dest: /etc/kubernetes/manifests/kube-scheduler.yaml
    replace: '    imagePullPolicy: Always'
    regexp: '^    imagePullPolicy: IfNotPresent'

- name: Update kube-apiserver admission controller to add AlwaysPullImages and ResourceQuota
  replace:
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    regexp: '^    - --enable-admission-plugins=.*'
    replace: '    - --enable-admission-plugins=NodeRestriction'

- name: Update the etcd image to point to the original Instance
  replace:
    dest: /etc/kubernetes/manifests/etcd.yaml
    regexp: '^    image:.*'
    replace: '    image: registry.k8s.io/etcd:3.5.5-0'

- name: Update the kube-apiserver image to point to the original Instance
  replace:
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    regexp: '^    image:.*'
    replace: '    image: registry.k8s.io/kube-apiserver:v1.25.7'

- name: Update the kube-controller-manager image to point to the original Instance
  replace:
    dest: /etc/kubernetes/manifests/kube-controller-manager.yaml
    regexp: '^    image:.*'
    replace: '    image: registry.k8s.io/kube-controller-manager:v1.25.7'

- name: Update the kube-scheduler image to point to the original Instance
  replace:
    dest: /etc/kubernetes/manifests/kube-scheduler.yaml
    regexp: '^    image:.*'
    replace: '    image: registry.k8s.io/kube-scheduler:v1.25.7'

