# ignoring errors in case the lock isn't in place yet. It will error and fail without it
---
- name: Install versionlock
  yum:
    name: yum-plugin-versionlock
    state: latest


- name: Install kubernetes.repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: "0600"

- name: Install stable.repo
  copy:
    src: stable.repo
    dest: /etc/yum.repos.d/stable.repo
    owner: root
    group: root
    mode: "0600"

- name: Install crio.repo
  copy:
    src: crio.repo
    dest: /etc/yum.repos.d/crio.repo
    owner: root
    group: root
    mode: "0600"
  when: "'kube' in inventory_hostname"


- name: Delete versionlock for kubelet
  command: /usr/bin/yum versionlock delete "kubelet.*"
  ignore_errors: yes

- name: Delete versionlock for kubectl
  command: /usr/bin/yum versionlock delete "kubectl.*"
  ignore_errors: yes

- name: Delete versionlock for kubeadm
  command: /usr/bin/yum versionlock delete "kubeadm.*"
  ignore_errors: yes

- name: Delete versionlock for kubernetes-cni
  command: /usr/bin/yum versionlock delete "kubernetes-cni.*"
  ignore_errors: yes

- name: Delete versionlock for cri-o
  command: /usr/bin/yum versionlock delete "cri-o.*"
  ignore_errors: yes
  when: "'kube' in inventory_hostname"


- name: Delete versionlock for docker-rhel-push-plugin
  command: /usr/bin/yum versionlock delete "docker-rhel-push-plugin.*"
  ignore_errors: yes

- name: Delete versionlock for docker-common
  command: /usr/bin/yum versionlock delete "docker-common.*"
  ignore_errors: yes

- name: Delete versionlock for docker-client
  command: /usr/bin/yum versionlock delete "docker-client.*"
  ignore_errors: yes

- name: Delete versionlock for docker
  command: /usr/bin/yum versionlock delete "docker.*"
  ignore_errors: yes


- name: Lock kubelet at 1.25.4
  command: /usr/bin/yum versionlock add "kubelet-1.25.4-0.*"

- name: Lock kubectl at 1.25.4
  command: /usr/bin/yum versionlock add "kubectl-1.25.4-0.*"

- name: Lock kubeadm at 1.25.4
  command: /usr/bin/yum versionlock add "kubeadm-1.25.4-0.*"

- name: Lock kubernetes-cni at 1.2.0-0
  command: /usr/bin/yum versionlock add "kubernetes-cni-1.2.0-0*"

- name: Lock cri-o at 1.24.4-3.2
  command: /usr/bin/yum versionlock add "cri-o-1.24.4-3.2*"
  when: "'kube' in inventory_hostname"

- name: Lock docker at 1.13.1-209
  command: /usr/bin/yum versionlock "docker-1.13.1-209.*"

- name: Lock docker-common at 1.13.1-209
  command: /usr/bin/yum versionlock "docker-common-1.13.1-209.*"

- name: Lock docker-client at 1.13.1-209
  command: /usr/bin/yum versionlock "docker-client-1.13.1-209.*"

- name: Lock docker-rhel-push-plugin at 1.13.1-209
  command: /usr/bin/yum versionlock "docker-rhel-push-plugin-1.13.1-209.*"


- name: Install kubelet
  yum:
    name: kubelet-1.25.4-0.x86_64
    state: present
    disable_gpg_check: yes

- name: Install kubectl
  yum:
    name: kubectl-1.25.4-0.x86_64
    state: present
    disable_gpg_check: yes

- name: Install kubeadm
  yum:
    name: kubeadm-1.25.4-0.x86_64
    state: present
    disable_gpg_check: yes

- name: Install kubernetes-cni
  yum:
    name: kubernetes-cni-1.2.0-0.x86_64
    state: present
    disable_gpg_check: yes

- name: Install cri-o
  yum:
    name: cri-o-1.24.4-3.2
    state: present
    disable_gpg_check: yes
  when: "'kube' in inventory_hostname"


- name: Install docker
  yum:
    name: docker-1.13.1-209.git7d71120.el7*
    state: present
    disable_gpg_check: yes

- name: Install docker-common
  yum:
    name: docker-common-1.13.1-209.git7d71120.el7*
    state: present
    disable_gpg_check: yes

- name: Install docker-client
  yum:
    name: docker-client-1.13.1-209.git7d71120.el7*
    state: present
    disable_gpg_check: yes

- name: Install docker-rhel-push-plugin
  yum:
    name: docker-rhel-push-plugin-1.13.1-204.git0be3e21.el7*
    state: present
    disable_gpg_check: yes
  ignore_errors: yes

