---
- name: Install docker
  yum:
    name: docker
    state: latest

- name: Enable the docker service
  systemd:
    name: docker
    enabled: yes

- name: Start docker
  systemd:
    name: docker
    state: started

- name: Install versionlock
  yum:
    name: yum-plugin-versionlock
    state: latest

- name: Lock kubelet at 1.14.7
  command: /usr/bin/yum versionlock "kubelet-1.14.7-0.*"

- name: Lock kubectl at 1.14.7
  command: /usr/bin/yum versionlock "kubectl-1.14.7-0.*"

- name: Lock kubeadm at 1.14.7
  command: /usr/bin/yum versionlock "kubeadm-1.14.7-0.*"

- name: Install kubelet
  yum:
    name: kubelet-1.14.7-0.x86_64 
    state: present

- name: Install kubectl
  yum:
    name: kubectl-1.14.7-0.x86_64 
    state: present

- name: Install kubeadm
  yum:
    name: kubeadm-1.14.7-0.x86_64 
    state: present

- name: Enable the kubelet service
  systemd:
    name: kubelet
    enabled: yes

